[package]
name = "email-troll"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
reqwest = "0.11"
clap = { version = "3.2", features = ["derive"] }
cargo = "0.63"
